#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BRANCH=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
PROTECTED_BRANCHES="^(main|development|staging)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and use PR.\n" && exit 1
fi

npx nx affected --target=build --project=frontend --base=origin/development --configuration=development
if [[ $? -ne 0 ]] ; then
   echo -e "\n🚫 Build Failed. \n" && exit 1
fi
